### ISSUE TITLE
can't start it

### ISSUE THREAD

**Issue by romanesko** [hef/imgui-in-browser#1]
scons: Reading SConscript files ...
KeyError: 'EMSDK':
  File "/build/SConstruct", line 38:
    env['ENV']['PATH'] += ':{}'.format(env['EMSDK'])
  File "/usr/lib/scons/SCons/Environment.py", line 410:
    return self._dict[key]

**Comment by hef** [comment]
does 242cf45c10f26d6c1ffbaaa71e3b0b033002a4b8 fix your issue?

**Comment by hef** [comment]
actually, are you running scons inside the docker container or outside of it?

I'm not sure what would cause that error from inside.

If you want to run scons outside the docker container, you need to setup emsdk (see http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html) and then run `scons EMSDK=/path/to/emsdk`

**Comment by allbombson** [comment]
I got same error when running inside.

**Comment by allbombson** [comment]
Update: worked by running "scons EMSDK=$EMSDK"
